version: '3.3'
services:
    oracledb_21:
        container_name: oracle_pao
        ports:
            - '1521:1521'
            - '5500:5500'
            - '2484:2484'
        environment:
            - ORACLE_PWD=fmilove
            - ENABLE_ARCHIVELOG=true
            - ENABLE_TCPS=true
        image: container-registry.oracle.com/database/express:latest
        networks:
          static-network:
            ipv4_address: 172.21.128.2
        volumes:
          - ./:/app
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.21.0.0/16
