name: Java CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
          
      - name: Step 3 - Get Maven project version
        id: get-version
        run: echo "project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Step 4 - Build Maven Project
        run: mvn package -B
        
#      - name: Step 5 - Upload release asset
#        uses: actions/upload-artifact@v2
#        with:
#          name: release-package
#          path: target/VintageRent-${{ env.project_version }}.jar

      - name: Step 5 - Create release package
        id: create_release
        uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.project_version }}"
          prerelease: true
          title: "VintageRent ${{ env.project_version }}
          files: |
            "target/VintageRent-${{ env.project_version }}.jar"
