name: CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - have GitHub Actions Build Maven Project
      run: mvn --batch-mode --update-snapshots verify
    
    - name: Step 4 - Make staging directory
      run: mkdir staging && cp target/*.jar staging
      
    - name: Step 5 - Upload package
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging
