name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v3

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'
          cache: maven
          
      - name: Step 3 - Get Maven project version
        id: get-version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

      - name: Step 4 - have GitHub Actions Build Maven Project
        run: mvn package -B

      - name: Step 5 - Create release package
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-version.outputs.version }}
          release_name: This is version ${{ steps.get-version.outputs.version }} of the project.
          body: This is version ${{ steps.get-version.outputs.version }} of the project.
          draft: false
          prerelease: true
          files: |
            target/VintageRent-${{ steps.get-version.outputs.version }}.jar
